# Site settings
title: freeCookieğŸª
SEOTitle: 
header-img: img/zhihu.jpg
email: 
description: ""
keyword: ""
url: "http://YijiaJin.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

# SNS settings
RSS: false
douban_username:  
twitter_username: YijiaJin
github_username: YijiaJin
facebook_username: 100009010019145
weibo_username: 
zhihu_username: yi-zhi-53
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: https-yijiajin-github-io

# Duoshuo settings
duoshuo_username:           # your username
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share:                      # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900

# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "â¤ï¸ ğŸ’› Lifelong Learner ğŸ’š ğŸ’™"
sidebar-avatar: /img/panda2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0.2              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "å…”å­ğŸ°",
        href: "https://yuchen9459.github.io/"
    },
    {
        title: "è¥¿ç“œğŸ‰",
        href: "https://littlenoah.github.io/"
    }
]

gem 'jekyll-paginate', group: :jekyll_plugins
