 # Site settings
title: freeCookie_å…è´¹å°ğŸª
header-img: "img/zhihu.jpg"
tagline: "cn"  
description: "å°ğŸªçš„ç”Ÿæ´»ç¬”è®°"  
baseurl: ""
url: "http://YijiaJin.github.io"  

# About/contact
owner: 
  name: " freeCookie_å…è´¹å°ğŸª"
  email: YijiaJin24@gmail.com
  bio: "å†™ä¸å‡ºå°±å»åƒå…è´¹é¥¼å¹²å¥½äº†~"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: YijiaJin
github_username: YijiaJin
facebook_username: 100009010019145
weibo_username: 
zhihu_username: yi-zhi-53

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "freeCookieğŸª"
      header-img: "img/star.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disque
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "freeCookie_ğŸª"
sidebar-avatar: /img/favicon.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0.2              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "å…”å­å¦ğŸ°ï¼ˆå¤§è¯¯ï¼‰", 
        href: "https://yuchen9459.github.io/"
    }
    {
        title: "è¥¿ç“œå›ğŸ‰ï¼ˆè¯¯ï¼‰",
        href: "https://littlenoah.github.io/"
    }
]

gem 'jekyll-paginate', group: :jekyll_plugins
